name: Terraform Plan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Setup Terraform
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          
      - name: Clean Terraform caches
        run: |
          rm -rf .terraform
          rm -f .terraform.lock.hcl
          rm -rf modules/templates/user-vm || true
          rm -rf modules/templates/*.tf || true


      - name: Terraform Init
        run: terraform init

      - name: Debug workspace
        run: |
          echo "=== Workspace contents ==="
          find . -maxdepth 4 -type f -print

      - name: Terraform Plan
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          PM_TLS_INSECURE: ${{ secrets.PM_TLS_INSECURE }}
        run: terraform plan -input=false
